sonar.projectKey=portfolio-full-stack
sonar.projectName=Portfolio Full Stack
sonar.projectVersion=1.0

# Code source
sonar.sources=backend_react

# Dossier des tests
sonar.tests=backend_react/tests

# Reconnaissance des fichiers tests
sonar.test.inclusions=**/*.test.js

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/.git/**,frontend_react/**,**/coverage/**

# Coverage Jest
sonar.javascript.lcov.reportPaths=backend_react/coverage/lcov.info

# Working directory
sonar.working.directory=.scannerwork